.Rbuildignore
DESCRIPTION
R/riskmetric.R

* added `emmeans` code coverage
* used `BiocPkgTools::biocPkgList` to get analogous fields as CRAN db
* haven't yet re-generated dataset for package, wasn't sure how we wanted to version this on GitHub
* `Copyright` isn't an avaialble field from `biocPkgList`
* `limma` doesn't use a testing framework I'm familiar with, not sure how to test it

Added bioconductor fields and package coverage

---

DESCRIPTION
R/cran.R
man/get_cran_version.Rd
riskmetric.Rproj
tests/testthat/test_cran_metrics.R

I figured if we're operating on the `cran_db` data.frame that it would be good to be able to accommodate a situation where we want to pull a whole vector of version numbers. 
I also updated the test suite with a couple more tests to accommodate the new behavior.

Added handling of get_cran_version for vector of package names

---

R/pkg_ref.R

That's pretty much it, all there is to mimic call by reference. #20
Now you can basically store whatever you want in a pkg_reference and it should never get copied when you pass the thing around!

made package references environments for call by reference behaviour

---

R/pkg_ref_cache_help_aliases.R

Hi @dgkf and others - great package! In my initial playing around, i noticed that the help assessment only worked for `pkg_install`, and just errored for `pkg_source`. This is an initial step to extract help aliases for the latter. It then just needs to be plugged in to a matching [`assess_export_help.pkg_source` function](https://github.com/pharmaR/riskmetric/blob/master/R/assess_export_help.R#L18) and should work, but I thought I'd leave this initial PR lightweight to start with.

add pkg_ref_cache.help_aliases.pkg_source fn

---

vignettes/extending-riskmetric.Rmd
vignettes/riskmetric.Rmd

The main vignette one is just because it was confusingly formatted as a quote (and i took the opportunity to insert a hyperlink there).
The change in the extending vignette is important, because i read the previous version and though, oh, okay, `new_pkg_metric()` must be a function that i have to subsequently define somewhere. But no, it actually should be the generic `pkg_metric()`, with the function named after the class (`"pkg_metric_name_first_letter"`), and subsequently defined as a template specification on [`score`](https://github.com/pharmaR/riskmetric/blob/master/vignettes/extending-riskmetric.Rmd#L188-L190) - right? Happy to iterate if i have misunderstood ...

tiny vignette tidying

---

R/assess_downloads.r
R/pkg_ref_cache_downloads.R

- Moved `pkg_ref_cache.downloads` to separate file to be consistent with other `pkg_ref_cache` field implementations
- Updated some spacing and 80 char line width in roxygen headers

Minor refactoring for code style and structure consistency

---

tests/testthat/test_assess.R
tests/testthat/test_pkg_ref.R

Here are a couple of initial tests. I have a good idea of the package now and I have a few things I'm working on for other tests. This closes #95 
**pkg_ref**
Tests some basic tests around what should be returned in a couple of situations and if errors throw as expected.
**assess**
Check a few things about what is being returned.

Merge initial tests for `pkg_ref` and `assess`

---

R/pkg_ref_cache_covr_coverage.R

- Adds explicit package path to `covr::package_coverage` call
- Added a small comment to explain why we pass this expression to the covr call for anyone that happens to stumble up on this code.

explicitly declare covr package coverage path; Fixes #103

---

R/pkg_ref_cache_archive_release_date.R
R/pkg_ref_cache_maintainer.R
R/pkg_ref_cache_release_date.R
R/pkg_ref_cache_website_urls.R
tests/testthat/test_assess_export_help.R
tests/testthat/test_assess_has_news.R
tests/testthat/test_assess_has_vignettes.R
tests/testthat/test_assess_last_30_bugs_status.R
tests/testthat/test_assess_license.R
tests/testthat/test_assess_news_current.R
tests/testthat/test_package_1/DESCRIPTION
tests/testthat/test_package_1/NAMESPACE
tests/testthat/test_package_1/NEWS.md
tests/testthat/test_package_1/R/NAMESPACE
tests/testthat/test_package_1/R/test.R
tests/testthat/test_package_1/man/test.Rd
tests/testthat/test_package_2/DESCRIPTION
tests/testthat/test_package_2/R/NAMESPACE
tests/testthat/test_package_2/R/test.R

Per #127, This removes all rvest functions from the package and replaces them with xml2 and predicates. The logic for all of these comes from the bug_reports file. I tested it on a couple package and it all looks good to me.
There are a bunch of other things in the test directory that I have another PR for so we might want to wait to merge this in until that has gone through.
Example:
`
> coin_ref <- pkg_ref("coin")
> head(coin_ref$archive_release_dates)
name   version  date        
[1,] "coin" "0.2.10" "2005-05-04"
[2,] "coin" "0.2.11" "2005-06-02"
[3,] "coin" "0.2.12" "2005-06-15"
[4,] "coin" "0.2.13" "2005-07-11"
[5,] "coin" "0.2.14" "2005-07-26"
[6,] "coin" "0.2.6"  "2005-02-25"
> coin_ref$maintainer
[1] "Torsten Hothorn  <Torsten.Hothorn at R-project.org>"
> coin_ref$release_date
[1] …

Remove rvest

---

R/cran.R
tests/testthat/test_assess_export_help.R
tests/testthat/test_assess_has_news.R
tests/testthat/test_assess_has_vignettes.R
tests/testthat/test_assess_last_30_bugs_status.R
tests/testthat/test_assess_license.R
tests/testthat/test_assess_news_current.R

Following PR #117, I had somewhat disregarded maintenance of unit tests. I went through and tried to resolve as many as possible.
At this point I think that most of the current test cases are passing again. The only exception is the `bugs_status` tests. So far today I think I've exceeded my allowance for public github api requests, so it's now throwing errors, but I think it should be fine otherwise. However, I think we will have to look into spoofing the api endpoint so that we can decouple our tests from GitHub. 
For now I've disabled this test until we have something more reliable in the hopes of soon getting us back on track with some continuous integration to help with code review. 
I also took the liberty of removing some legacy tests we had in there from early on in the project. …

Getting unit tests passing again

---

R/pkg_score.R
man/pkg_score.Rd

`pkg_score()` now calculates the risk of using a package (rather than its quality). This PR updates the roxygen comments for this function accordingly.

Update roxygen function description for pkg_score

---

DESCRIPTION
tests/testthat/setup_mock_web_requests.R
tests/testthat/test_riskmetric_remotes.R

- updating github issues webmock
- switch to remote webmockr dependency
- add test for upcoming webmockr release

use remote dependency webmockr

---

README.md

Updating the badge to reflect our shift from travis to GitHub actions so that it reflects our build status properly

Updating to R-CMD-check GitHub action badge, fixed example

---

DESCRIPTION

`jsonlite` is unused in package code, and only used in tests. Moving to `Suggests` section of depends.

[R CMD check fix] moving jsonlite to suggests

---

README.md

The package is now on CRAN, so the readme was outdated.

Adds install.packages() instruction to readme

---

R/pkg_ref_cache_news.R

Warning message is returned, when running "assess_has_news" on packages, that do not have empty line at the end of file:
I have tested it on packages "ini", "viridisLite". Below is the code for reproducing the warning messages.
```
library("riskmetric")
library("magrittr")
dir.create(paste0(tempdir(), "/test_riskmetric"))
dir.create(paste0(tempdir(), "/test_riskmetric/source"))
dir.create(paste0(tempdir(), "/test_riskmetric/library"))
dir.create(paste0(tempdir(), "/test_riskmetric/downloads"))
pkgs <- c("viridisLite", "ini")
install.packages(pkgs, lib = paste0(tempdir(), "/test_riskmetric/library"))
list.files(paste0(tempdir(), "/test_riskmetric/library"), recursive = TRUE)
pkg_ref(x = paste0(tempdir(), "/test_riskmetric/library/", pkgs[1])) %>% 
pkg_assess(assessments = …
```

ignore incomplete final line

---

DESCRIPTION
R/pkg_ref_class.R
man/determine_pkg_source.Rd
man/pkg_assess.Rd

Fix typo in determine_pkg_source() docs

---

DESCRIPTION
NEWS.md
R/assess_size_codebase.R

Closes #362 
This change is related to assess_size_codebase metric, when it is being assessed on a local source code. It currently fails for packages that have .rda files inside the R folder. Examples: [acss.data](https://cran.r-project.org/web/packages/acss.data/index.html), [bayesPop](https://cran.r-project.org/web/packages/bayesPop/index.html).
The proposed change is to only list files with .R extension.

Limit assess_size_codebase to only .R files

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION
R/assess_dependencies.R
cran-comments.md

From [R-devel news](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html):
> grep(), strsplit() and similar took non-TRUE values of their logical arguments as FALSE, but these were almost always mistakes and are now reported as NA.
There was an error in the dependency check for source packages. and removing the extra `strsplit` fixes it

Updates to resolve CRAN comments in R-devel

---

R/pkg_ref_cache_archive_release_date.R
R/pkg_ref_class.R

Removes the `package_version` casting. 
This will enable it to work on old versions of packages before there was a requirement on what was allowed as version number. 
Note: R doesn't force semantic versioning (three numbers). 
Closes #364

Remove package_version

---

vignettes/extending-riskmetric.Rmd

This reduces calculation of some steps on the vignette.
Locally it was failing because `has_news` was not available. I changed to a different metric. 
I think `pkg_score` would benefit from some defensive programming (checking that the tibble has more than 1 column), but I haven't pushed that change.

Vignette improvements

---

.github/workflows/R-CMD-check.yaml

close #383 
Ubuntu 20.04 LTS actions runner image is now [deprecated](https://github.com/actions/runner-images/issues/11101).

remove deprecated ubuntu 20.04 from gha

---

R/assess_export_help.R

close #381 
The function `assess_export_help.pkg_source()` fails when the target package (i.e., the one being assessed) has dependencies that are not installed. This is due to the use of `pkgload::parse_ns_file()`, which attempts to evaluate `import()` and other namespace directives, thus requiring all dependencies to be present.
This makes the metric fragile and unsuitable for use in minimal environments (e.g., CI pipelines or isolated testing setups) where not all dependencies of a package are guaranteed to be installed.

bugfix: assess_export_help.pkg_source
